[phases.setup]
nixPkgs = ['python311', 'pip']

[phases.install]
cmd = 'pip install -r requirements.txt'

[phases.build]
cmd = 'echo "No build step needed"'

[start]
cmd = 'uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 1'